export type BibleBook = {
  id: string;
  name: string;
  chapters: number;
  category: "ot" | "nt" | "apocrypha";
};

export const BIBLE_BOOKS: BibleBook[] = [
  // Old Testament
  { id: "gen", name: "Genesis", chapters: 50, category: "ot" },
  { id: "exo", name: "Exodus", chapters: 40, category: "ot" },
  { id: "lev", name: "Leviticus", chapters: 27, category: "ot" },
  { id: "num", name: "Numbers", chapters: 36, category: "ot" },
  { id: "deu", name: "Deuteronomy", chapters: 34, category: "ot" },
  { id: "jos", name: "Joshua", chapters: 24, category: "ot" },
  { id: "jdg", name: "Judges", chapters: 21, category: "ot" },
  { id: "rut", name: "Ruth", chapters: 4, category: "ot" },
  { id: "1sa", name: "1 Samuel", chapters: 31, category: "ot" },
  { id: "2sa", name: "2 Samuel", chapters: 24, category: "ot" },
  { id: "1ki", name: "1 Kings", chapters: 22, category: "ot" },
  { id: "2ki", name: "2 Kings", chapters: 25, category: "ot" },
  { id: "1ch", name: "1 Chronicles", chapters: 29, category: "ot" },
  { id: "2ch", name: "2 Chronicles", chapters: 36, category: "ot" },
  { id: "ezr", name: "Ezra", chapters: 10, category: "ot" },
  { id: "neh", name: "Nehemiah", chapters: 13, category: "ot" },
  { id: "est", name: "Esther", chapters: 10, category: "ot" },
  { id: "job", name: "Job", chapters: 42, category: "ot" },
  { id: "psa", name: "Psalms", chapters: 150, category: "ot" },
  { id: "pro", name: "Proverbs", chapters: 31, category: "ot" },
  { id: "ecc", name: "Ecclesiastes", chapters: 12, category: "ot" },
  { id: "son", name: "Song of Solomon", chapters: 8, category: "ot" },
  { id: "isa", name: "Isaiah", chapters: 66, category: "ot" },
  { id: "jer", name: "Jeremiah", chapters: 52, category: "ot" },
  { id: "lam", name: "Lamentations", chapters: 5, category: "ot" },
  { id: "eze", name: "Ezekiel", chapters: 48, category: "ot" },
  { id: "dan", name: "Daniel", chapters: 12, category: "ot" },
  { id: "hos", name: "Hosea", chapters: 14, category: "ot" },
  { id: "joe", name: "Joel", chapters: 3, category: "ot" },
  { id: "amo", name: "Amos", chapters: 9, category: "ot" },
  { id: "oba", name: "Obadiah", chapters: 1, category: "ot" },
  { id: "jon", name: "Jonah", chapters: 4, category: "ot" },
  { id: "mic", name: "Micah", chapters: 7, category: "ot" },
  { id: "nah", name: "Nahum", chapters: 3, category: "ot" },
  { id: "hab", name: "Habakkuk", chapters: 3, category: "ot" },
  { id: "zep", name: "Zephaniah", chapters: 3, category: "ot" },
  { id: "hag", name: "Haggai", chapters: 2, category: "ot" },
  { id: "zec", name: "Zechariah", chapters: 14, category: "ot" },
  { id: "mal", name: "Malachi", chapters: 4, category: "ot" },

  // Apocrypha (Common selection)
  { id: "tob", name: "Tobit", chapters: 14, category: "apocrypha" },
  { id: "jdt", name: "Judith", chapters: 16, category: "apocrypha" },
  {
    id: "add_est",
    name: "Additions to Esther",
    chapters: 6,
    category: "apocrypha",
  },
  { id: "wis", name: "Wisdom of Solomon", chapters: 19, category: "apocrypha" },
  { id: "sir", name: "Sirach", chapters: 51, category: "apocrypha" },
  { id: "bar", name: "Baruch", chapters: 6, category: "apocrypha" },
  {
    id: "add_dan",
    name: "Additions to Daniel",
    chapters: 3,
    category: "apocrypha",
  }, // Song of Three, Susanna, Bel and Dragon usually grouped or separate. Keeping simple.
  { id: "1ma", name: "1 Maccabees", chapters: 16, category: "apocrypha" },
  { id: "2ma", name: "2 Maccabees", chapters: 15, category: "apocrypha" },

  // New Testament
  { id: "mat", name: "Matthew", chapters: 28, category: "nt" },
  { id: "mar", name: "Mark", chapters: 16, category: "nt" },
  { id: "luk", name: "Luke", chapters: 24, category: "nt" },
  { id: "joh", name: "John", chapters: 21, category: "nt" },
  { id: "act", name: "Acts", chapters: 28, category: "nt" },
  { id: "rom", name: "Romans", chapters: 16, category: "nt" },
  { id: "1co", name: "1 Corinthians", chapters: 16, category: "nt" },
  { id: "2co", name: "2 Corinthians", chapters: 13, category: "nt" },
  { id: "gal", name: "Galatians", chapters: 6, category: "nt" },
  { id: "eph", name: "Ephesians", chapters: 6, category: "nt" },
  { id: "phi", name: "Philippians", chapters: 4, category: "nt" },
  { id: "col", name: "Colossians", chapters: 4, category: "nt" },
  { id: "1th", name: "1 Thessalonians", chapters: 5, category: "nt" },
  { id: "2th", name: "2 Thessalonians", chapters: 3, category: "nt" },
  { id: "1ti", name: "1 Timothy", chapters: 6, category: "nt" },
  { id: "2ti", name: "2 Timothy", chapters: 4, category: "nt" },
  { id: "tit", name: "Titus", chapters: 3, category: "nt" },
  { id: "phm", name: "Philemon", chapters: 1, category: "nt" },
  { id: "heb", name: "Hebrews", chapters: 13, category: "nt" },
  { id: "jam", name: "James", chapters: 5, category: "nt" },
  { id: "1pe", name: "1 Peter", chapters: 5, category: "nt" },
  { id: "2pe", name: "2 Peter", chapters: 3, category: "nt" },
  { id: "1jo", name: "1 John", chapters: 5, category: "nt" },
  { id: "2jo", name: "2 John", chapters: 1, category: "nt" },
  { id: "3jo", name: "3 John", chapters: 1, category: "nt" },
  { id: "jud", name: "Jude", chapters: 1, category: "nt" },
  { id: "rev", name: "Revelation", chapters: 22, category: "nt" },
];
